### ISSUE TITLE
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with signal SIGKILL

### ISSUE THREAD

**Issue by Seventeen1711** [lyu-yx/ACUMEN#4]
File "/home/wsn/anaconda3/envs/wsn/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
           │               │   │     │       │     └ False
           │               │   │     │       └ True
           │               │   │     └ 2
           │               │   └ (CfgNode({'train_root': 'dataset/TrainDataset/', 'test_root': 'dataset/TestDataset/', 'val_root': 'dataset/TestDataset/CAMO/'...
           │               └ <function main_worker at 0x7fdd8b3a83a0>
           └ <function start_processes at 0x7fde2390f550>
  File "/home/wsn/anaconda3/envs/wsn/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
              │       └ <function ProcessContext.join at 0x7fde2390f700>
              └ <torch.multiprocessing.spawn.ProcessContext object at 0x7fdd8b2b4730>
  File "/home/wsn/anaconda3/envs/wsn/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 130, in join
    raise ProcessExitedException(
          └ <class 'torch.multiprocessing.spawn.ProcessExitedException'>

torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with signal SIGKILL
please，how to deal with this problem?

**Comment by lyu-yx** [comment]
Hi there,

You seems encountered multiprocess problem, could you bring more information? It is hard to find the chief culprit under current description. Also, I recommend to use debug or print to see the true line you stucked.

Best

**Comment by Seventeen1711** [comment]
2025-02-11 17:38:53.115 | ERROR    | __main__:<module>:223 - An error has been caught in function '<module>', process 'MainProcess' (818814), thread 'MainThread' (140366813673280):
Traceback (most recent call last):

> File "train_multigpu_noattr.py", line 223, in <module>
    main()
    └ <function main at 0x7fa90e6489d0>

  File "train_multigpu_noattr.py", line 71, in main
    mp.spawn(main_worker, nprocs=args.ngpus_per_node, args=(args, shared_vars))
    │  │     │                   │                          │     └ <DictProxy object, typeid 'dict' at 0x7fa9a57d1a90>
    │  │     │                   │                          └ CfgNode({'train_root': 'dataset/TrainDataset/', 'test_root': 'dataset/TestDataset/', 'val_root': 'dataset/TestDataset/CAMO/',...
    │  │     │                   └ CfgNode({'train_root': 'dataset/TrainDataset/', 'test_root': 'dataset/TestDataset/', 'val_root': 'dataset/TestDataset/CAMO/',...
    │  │     └ <function main_worker at 0x7fa90e648ca0>
    │  └ <function spawn at 0x7fa9acc0b040>
    └ <module 'torch.multiprocessing' from '/home/wsn/anaconda3/envs/wsn/lib/python3.8/site-packages/torch/multiprocessing/__init__...

  File "/home/wsn/anaconda3/envs/wsn/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
           │               │   │     │       │     └ False
           │               │   │     │       └ True
           │               │   │     └ 2
           │               │   └ (CfgNode({'train_root': 'dataset/TrainDataset/', 'test_root': 'dataset/TestDataset/', 'val_root': 'dataset/TestDataset/CAMO/'...
           │               └ <function main_worker at 0x7fa90e648ca0>
           └ <function start_processes at 0x7fa9acc09d30>
  File "/home/wsn/anaconda3/envs/wsn/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
              │       └ <function ProcessContext.join at 0x7fa9acc09ee0>
              └ <torch.multiprocessing.spawn.ProcessContext object at 0x7fa905bfe2b0>
  File "/home/wsn/anaconda3/envs/wsn/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
          │                      │    │            │              └ <property object at 0x7fa9acc4c040>
          │                      │    │            └ <SpawnProcess name='SpawnProcess-2' pid=818852 parent=818814 stopped exitcode=1>
          │                      │    └ 0
          │                      └ '\n\n-- Process 0 terminated with the following error:\nTraceback (most recent call last):\n  File "/home/wsn/anaconda3/envs/...
          └ <class 'torch.multiprocessing.spawn.ProcessRaisedException'>

torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/wsn/anaconda3/envs/wsn/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/tmp/wsn/ACUMEN-main/train_multigpu_noattr.py", line 199, in main_worker
    train(train_loader, model, optimizer, scheduler, scaler, epoch_log, args)
  File "/tmp/wsn/ACUMEN-main/engine/engine.py", line 51, in train
    pred, fix_out, total_loss, fix_loss, kl_loss, cc_loss, mask_loss, consistency_loss, attr_loss = model(img, img_gt, overall_desc, camo_desc, attr, fix_gt)
  File "/home/wsn/anaconda3/envs/wsn/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wsn/anaconda3/envs/wsn/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 799, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/wsn/anaconda3/envs/wsn/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/tmp/wsn/ACUMEN-main/model/clipcod.py", line 121, in forward
    vis = self.backbone.encode_image(img)           # list: 3 x [b, 576, 768]
  File "/tmp/wsn/ACUMEN-main/model/clip.py", line 472, in encode_image
    return self.visual(image.type(self.dtype))
  File "/home/wsn/anaconda3/envs/wsn/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/tmp/wsn/ACUMEN-main/model/clip.py", line 349, in forward
    x = self.transformer(x)
  File "/home/wsn/anaconda3/envs/wsn/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/tmp/wsn/ACUMEN-main/model/clip.py", line 287, in forward
    x = resblock(x)
  File "/home/wsn/anaconda3/envs/wsn/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/tmp/wsn/ACUMEN-main/model/clip.py", line 264, in forward
    x = x + self.mlp(self.ln_2(x))
  File "/home/wsn/anaconda3/envs/wsn/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/tmp/wsn/ACUMEN-main/model/clip.py", line 230, in forward
    ret = super().forward(x.type(torch.float32))
  File "/home/wsn/anaconda3/envs/wsn/lib/python3.8/site-packages/torch/nn/modules/normalization.py", line 173, in forward
    return F.layer_norm(
  File "/home/wsn/anaconda3/envs/wsn/lib/python3.8/site-packages/torch/nn/functional.py", line 2346, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 10.75 GiB total capacity; 9.45 GiB already allocated; 2.00 MiB free; 9.61 GiB reserved in total by PyTorch)

**Comment by lyu-yx** [comment]
Hi @Seventeen1711 

It is obvious that is an out of memory problem. Current settings is based on RTX8000 which has 40G GPU memory. Try to decrease the batch size or input size and try again.

Best,
Yixuan

**Comment by Seventeen1711** [comment]
025-02-17 23:56:40.755 | ERROR    | __main__:<module>:223 - An error has been caught in function '<module>', process 'MainProcess' (2920579), thread 'MainThread' (140451209770048):
Traceback (most recent call last):

> File "/data00/home/lyl/ACUMEN-main/train_multigpu_noattr.py", line 223, in <module>
    main()
    └ <function main at 0x7fbbe6f90040>

  File "/data00/home/lyl/ACUMEN-main/train_multigpu_noattr.py", line 70, in main
    mp.spawn(main_worker, nprocs=args.ngpus_per_node, args=(args, shared_vars))
    │  │     │                   │                          │     └ <DictProxy object, typeid 'dict' at 0x7fbbe6fa4550>
    │  │     │                   │                          └ CfgNode({'train_root': 'dataset/TrainDataset/', 'test_root': 'dataset/TestDataset/', 'val_root': 'dataset/TestDataset/CAMO/',...
    │  │     │                   └ CfgNode({'train_root': 'dataset/TrainDataset/', 'test_root': 'dataset/TestDataset/', 'val_root': 'dataset/TestDataset/CAMO/',...
    │  │     └ <function main_worker at 0x7fbbe6f90310>
    │  └ <function spawn at 0x7fbc9e680ee0>
    └ <module 'torch.multiprocessing' from '/data00/home/lyl/miniconda3/envs/SD/lib/python3.10/site-packages/torch/multiprocessing/...

  File "/data00/home/lyl/miniconda3/envs/SD/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 246, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
           │               │   │     │       │     └ False
           │               │   │     │       └ True
           │               │   │     └ 1
           │               │   └ (CfgNode({'train_root': 'dataset/TrainDataset/', 'test_root': 'dataset/TestDataset/', 'val_root': 'dataset/TestDataset/CAMO/'...
           │               └ <function main_worker at 0x7fbbe6f90310>
           └ <function start_processes at 0x7fbc9e680c10>
  File "/data00/home/lyl/miniconda3/envs/SD/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 202, in start_processes
    while not context.join():
              │       └ <function ProcessContext.join at 0x7fbc9e680dc0>
              └ <torch.multiprocessing.spawn.ProcessContext object at 0x7fbbe6fb0280>
  File "/data00/home/lyl/miniconda3/envs/SD/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 163, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
          │                      │    │            │              └ <property object at 0x7fbc9e6272e0>
          │                      │    │            └ <SpawnProcess name='SpawnProcess-2' pid=2920652 parent=2920579 stopped exitcode=1>
          │                      │    └ 0
          │                      └ '\n\n-- Process 0 terminated with the following error:\nTraceback (most recent call last):\n  File "/data00/home/lyl/minicond...
          └ <class 'torch.multiprocessing.spawn.ProcessRaisedException'>

torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/data00/home/lyl/miniconda3/envs/SD/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 74, in _wrap
    fn(i, *args)
  File "/data00/home/lyl/ACUMEN-main/train_multigpu_noattr.py", line 199, in main_worker
    train(train_loader, model, optimizer, scheduler, scaler, epoch_log, args)
  File "/data00/home/lyl/ACUMEN-main/engine/engine.py", line 51, in train
    pred, fix_out, total_loss, fix_loss, kl_loss, cc_loss, mask_loss, consistency_loss, attr_loss = model(img, img_gt, overall_desc, camo_desc, attr, fix_gt)
  File "/data00/home/lyl/miniconda3/envs/SD/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data00/home/lyl/miniconda3/envs/SD/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data00/home/lyl/miniconda3/envs/SD/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1519, in forward
    else self._run_ddp_forward(*inputs, **kwargs)
  File "/data00/home/lyl/miniconda3/envs/SD/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1355, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
  File "/data00/home/lyl/miniconda3/envs/SD/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data00/home/lyl/miniconda3/envs/SD/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data00/home/lyl/ACUMEN-main/model/clipcod.py", line 129, in forward
    fix_out, fix_tensor = self.fix_encoder(vis)  # [b, 1, 96, 96]  [b, 576, 768]
  File "/data00/home/lyl/miniconda3/envs/SD/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data00/home/lyl/miniconda3/envs/SD/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data00/home/lyl/ACUMEN-main/model/layers.py", line 130, in forward
    fused_features = self.fusion(feature_list)
  File "/data00/home/lyl/miniconda3/envs/SD/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data00/home/lyl/miniconda3/envs/SD/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data00/home/lyl/ACUMEN-main/model/layers.py", line 108, in forward
    attn_output, _ = self.attention(query=query, key=kv, value=kv)
  File "/data00/home/lyl/miniconda3/envs/SD/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data00/home/lyl/miniconda3/envs/SD/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data00/home/lyl/miniconda3/envs/SD/lib/python3.10/site-packages/torch/nn/modules/activation.py", line 1241, in forward
    attn_output, attn_output_weights = F.multi_head_attention_forward(
  File "/data00/home/lyl/miniconda3/envs/SD/lib/python3.10/site-packages/torch/nn/functional.py", line 5346, in multi_head_attention_forward
    k = k.view(k.shape[0], bsz * num_heads, head_dim).transpose(0, 1)
RuntimeError: shape '[12, 4608, 96]' is invalid for input of size 15925248
please,how to deal with this problem?

**Comment by lyu-yx** [comment]
I notice that there is a 3 times relationship between 15925248 and [12 * 4608 * 96]. I think it should be the dimension difference of tensor. You can print the shape of tensor shape to align with layers' dimension.
